import type { NextPage } from "next";
import Head from "next/head";
import Search from "../components/Search"
import Nav from "../components/Nav"





const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Crytpo Prices</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Search />     
    </>
  );
};

export default Home;
