import type { NextPage } from "next";
import Head from "next/head";
import Search from "../components/Search"
// import Nav from "../components/Nav"
import { ThemeProvider, createTheme } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';

const darkTheme = createTheme({
  palette: {
    mode: 'dark',
  },
});

const Home: NextPage = () => {
  return (
    <>
      <ThemeProvider theme={darkTheme}>
        <CssBaseline>
          <Head>
            <title>Crytpo Prices</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          {/* <Nav /> */}
          <Search />  
        </CssBaseline>
      </ThemeProvider>   
    </>
  );
};

export default Home;
